### PR TITLE
get the users as png instead of wepm

### PR DESCRIPTION
**Pull request by sravan1946**

### CODE REVIEW

**Comment by TheF1ng3r** [comment]
@sravan1946 I don't see why you need to use png. Webp is more optimized and is better for images with non transparent backgrounds

**Comment by TheF1ng3r** [comment]
Oh didn't know about that

**Comment by TheF1ng3r** [comment]
@sravan1946 After looking through the pillow docs I found [this](https://pillow.readthedocs.io/en/stable/handbook/image-file-formats.html#webp) showing that it is supported

**Review by TheF1ng3r — COMMENTED** [review]
The code is good I just still don't see the purpose

**Comment by sravan1946** [comment]
The final image is send as a .png in discord. So why not just pull the image as png itself

**Review by TheF1ng3r — APPROVED** [review]
I now agree with this change, the code is good and shouldn't be breaking from just looking (I did not test)

**Review by phenom4n4n — CHANGES_REQUESTED** [review]
I don't see any reason why this would error, but could you confirm whether this has been tested before I merge it? Additionally, can you bump the cog's macro version and then run pre-commit?

**Comment by sravan1946** [comment]
I did test it(not on a raspberry pi cuz i dont have it) but it doesnt break on other.
and i am doing the pre-commit, but its not coming here for some reason

**Review by phenom4n4n — APPROVED** [review]

**Pull request merged**
