### PR TITLE
Add command to edit the tagscript from pastebin link

### PR DESCRIPTION
**Pull request by sravan1946**

### CODE REVIEW

**Comment by sravan1946** [comment]
couldn't name the command `append` cuz it was already used in the cog.¯\\_(ツ)_/¯

**Comment by flaree** [comment]
Just a comment while I seen this. Requests is blocking, you should use aiohttp for all requests as it's async. This applies to more than just this PR and isn't a review of any sort.

**Comment by sravan1946** [comment]
> 
> 
> Just a comment while I seen this. Requests is blocking, you should use aiohttp for all requests as it's async. This applies to more than just this PR and isn't a review of any sort.

i'm new in python and these stuff 😅

**Comment by phenom4n4n** [comment]
Thanks for opening this PR. I have a few requests for changes that should be made, but I'll post them here rather than in a review and make the changes myself.

- The actual Pastebin fetch logic should be handled in a subclass of TagScriptConverter for two reasons: The logic needs to be reused in a tag global command, and after fetching the Pastebin contents, it needs to be validated as safe tagscript.
- The fetch method should be done with aiohttp using `Tags.session` rather than requests which is blocking.
- The Pastebin regex should accept raw or regular Pastebin links, and then use the matched id to fetch from a raw Pastebin link.

**Comment by phenom4n4n** [comment]
I messed up git so I'll PR it myself. In the future, make sure to create a new branch to make pull requests from.

**Pull request closed without merging**
