### PR TITLE
[Tags]catch if message is deleted already before bot can delete

### PR DESCRIPTION
**Pull request by kablekompany**

### CODE REVIEW

**Comment by phenom4n4n** [comment]
This shouldn't be an issue since discord.HTTPException will catch it. Have you seen this error in a tag?

**Comment by kablekompany** [comment]
Yee
Case where some lag coerced user to delete after their invocation and got exception on tag process for that delete when the bot caught up to handle the task (as it was no longer there etc) 

I can give ss tomorrow when I'm at a console.

**Comment by kablekompany** [comment]
You're right it does inherit - I wonder if the exception is deriving from how the bot is slated to handle an HTTPException (which I would think would cover all tbh)
I'll load back to current revision, so I can be sure I snag the log capture. I've not seen it mishandle since adding the secondary except pass for NotFound but now I'm curious as to why I was getting it at all 

Reference:
```py
class NotFound(HTTPException)
 |  NotFound(response, message)
 |  
 |  Exception that's thrown for when status code 404 occurs.
 |  
 |  Subclass of :exc:`HTTPException`
 |  
 |  Method resolution order:
 |      NotFound
 |      HTTPException
 |      DiscordException
 |      builtins.Exception
 |      builtins.BaseException
 |      builtins.object
 |  
 |  Methods inherited from HTTPException:
 |  
 |  __init__(self, response, message)
 |      ...
```

**Comment by phenom4n4n** [comment]
Most likely this was due to trying to catch the exception while creating a task.. which was a mistake in the first place. It should've been gathering everything at once rather than creating a task. I updated the code last night to gather everything at the end rather than create a task to avoid requests causing slower response time.

**Pull request closed without merging**
